services:
  postgres:
    image: postgres:latest
    container_name: social_network_postgres
    restart: always
    environment:
      POSTGRES_DB: social_network_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1526
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
